### ISSUE TITLE
CUDA out of memory seq2_attr

### ISSUE THREAD

**Issue by YingboHuang** [buenrostrolab/scPrinter#83]
I have encounter error related to resources limits when running 
`seq2print_attr --pt /mnt/storage/home/yh821/ATAC/scPrinter_tutorial//seq2print/model/PBMC_bulkATAC_0_frags_fold0-stoic-fog-5.pt --peaks /mnt/storage/home/yh821/ATAC/scPrinter_tutorial//seq2print/seq2print_cleaned_narrowPeak.bed --method shap_hypo --wrapper count --nth_output 0 --gpus 0 --genome hg38 --decay 0.85 --save_key deepshap --overwrite --model_norm count --sample 30000 --save_norm`

RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 11.17 GiB total capacity; 10.18 GiB already allocated; 87.19 MiB free; 10.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I have tried to `export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128 && CUDA_VISIBLE_DEVICES=0 seq2print_attr --pt /mnt/storage/home/yh821/ATAC/scPrinter_tutorial//seq2print/model/PBMC_bulkATAC_0_frags_fold0-stoic-fog-5.pt --peaks /mnt/storage/home/yh821/ATAC/scPrinter_tutorial//seq2print/seq2print_cleaned_narrowPeak.bed --method shap_hypo --wrapper count --nth_output 0 --gpus 0 --genome hg38 --decay 0.85 --save_key deepshap --overwrite --model_norm count --sample 5000 --save_norm` but it returns same error. 

While I am looking for other GPU resource available, I am wondering if there is a way to reduce memory needs, since the GPU resource i have is limited... 

Does reduce the peak number from peak call(eg. p < 1e-5 instead of 0.01) will reduce the memory needs?

Thank you very much,
Yingbo

**Comment by ruochiz** [comment]
Hi, I think the GPU you have is right on the edge. The seq2attr would requires around 10.1GB + some caching space to run. 
Reducing the number of peaks won't help since the code is already loading only one peak at a time to calculate attributions. 

https://github.com/buenrostrolab/scPrinter/blob/6edde7445f0e0b5da598f19338d8d167122db459/scprinter/seq/scripts/evaluation_model.py#L482

```
 attributions = calculate_attributions(
                model,
                X=dataset.cache_seqs[random_ids],
                n_shuffles=20,
                method=method,
                verbose=False if len(ids) > 1 else verbose,
            )
```
 you can change the n_shuffles to sth smaller and reinstall the package to reduce the memory (at the cost of less reliable sequence attribution scores.)

**Comment by YingboHuang** [comment]
I kind of feel the same. Let me try to get other gpu resource and try, current tried k80 and T4 for bulk ATAC data. They all run pretty slow with each epoch took 2-3 hours for ~13000 peaks.

**Comment by HYsxe** [comment]
@YingboHuang Hi Yingbo! I'm following up to see if you were able to resolve the issue and get the tool running properly. Let us know!

**Comment by YingboHuang** [comment]
yes! Thanks for checking in. I was able to run the seq2print using other GPU with fold=1. Have not yet try anything more than that. Feel free to resolve this issue.
